variables_label = {
    "10m_component_of_wind": "Velocidad del viento a 10 metros de la superficie",
    "10m_u_component_of_wind": "Velocidad del viento a 10 metros de la superficie",
    "10m_v_component_of_wind": "Velocidad del viento a 10 metros de la superficie",
    "temperature": "Temperatura",
    "2m_temperature": "Temperatura a 2 metros de la superficie",
    "angle_of_sub_gridscale_orography": "Ángulo de la orografía a escala subcuadrícula",
    "anisotropy_of_sub_gridscale_orography": "Anisotropía de la orografía a escala subcuadrícula",
    "geopotential": "Geopotencial",
    "geopotential_at_surface": "Geopotencial en la superficie",
    "high_vegetation_cover": "Covertura de vegetación",
    "type_of_high_vegetation": "Tipo de vegetación",
    "lake_cover": "Covertura de lagos",
    "land_sea_mask": "Segmentación entre tierra y mar",
    "low_vegetation_cover": "Cobertura de vegetación baja",
    "mean_sea_level_pressure": "Presión media a nivel del mar",
    "sea_ice_cover": "Covertura de hielo en el mar",
    "sea_surface_temperature": "Temperatura en la superfice del mar",
    "slope_of_sub_gridscale_orography": "Pendiente de la orografía",
    "soil_type": "Tipo de suelo",
    "specific_humidity": "Humedad específica",
    "standard_deviation_of_filtered_subgrid_orography": "Desviación estándar de la orografía filtrada",
    "standard_deviation_of_orography": "Desviación estándar de la orografía",
    "surface_pressure": "Presión en la superficie",
    "toa_incident_solar_radiation": "Radiación solar incidente",
    "total_cloud_cover": "Covertura total de nubes",
    "type_of_low_vegetation": "Tipo de vegetación baja",
    "component_of_wind": "Velocidad del viento",
    "u_component_of_wind": "La componente U (este-oeste) del viento",
    "v_component_of_wind":"La componente V (norte-sur) del viento",
    "vertical_velocity": "Velocidad vertical en la atmósfera",
}
